slice_name: Posizioni Debitorie create da file
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 2__table
  viz_type: big_number_total
  slice_id: 13
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: processed_rows
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 23
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      uuid: b91c1f30-5002-4144-8c6b-a02941bc83fb
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(processed_rows)
    optionName: metric_81nir97fn66_yek1ja8kg2p
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_r6yvgbb3ws_ah2jjt2x7nj
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: processed_time
  - clause: WHERE
    comparator:
    - INGESTION
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_j43idvd6hqj_d7mxlsh0pk6
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: event_type
  - clause: WHERE
    comparator:
    - DP_INSTALLMENTS
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_rx16hr17hhq_uq8n2dq6v9
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: flow_type
  header_font_size: 0.3
  subtitle: ''
  subtitle_font_size: 0.125
  show_metric_name: false
  metric_name_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 5
  annotation_layers: []
query_context: '{"datasource": {"id": 2, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "processed_time", "op": "TEMPORAL_RANGE", "val": "No filter"},
  {"col": "event_type", "op": "IN", "val": ["INGESTION"]}, {"col": "flow_type", "op":
  "IN", "val": ["DP_INSTALLMENTS"]}], "extras": {"having": "", "where": ""}, "applied_time_extras":
  {}, "columns": [], "metrics": [{"expressionType": "SIMPLE", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "processed_rows",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  23, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "BIGINT", "type_generic": 0, "uuid": "b91c1f30-5002-4144-8c6b-a02941bc83fb", "verbose_name":
  null, "warning_markdown": null}, "aggregate": "SUM", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "SUM(processed_rows)", "optionName": "metric_81nir97fn66_yek1ja8kg2p"}],
  "annotation_layers": [], "series_limit": 0, "group_others_when_limit_reached": false,
  "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data": {}}],
  "form_data": {"datasource": "2__table", "viz_type": "big_number_total", "slice_id":
  13, "metric": {"expressionType": "SIMPLE", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "processed_rows",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  23, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "BIGINT", "type_generic": 0, "uuid": "b91c1f30-5002-4144-8c6b-a02941bc83fb", "verbose_name":
  null, "warning_markdown": null}, "aggregate": "SUM", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "SUM(processed_rows)", "optionName": "metric_81nir97fn66_yek1ja8kg2p"},
  "adhoc_filters": [{"clause": "WHERE", "comparator": "No filter", "datasourceWarning":
  false, "expressionType": "SIMPLE", "filterOptionName": "filter_r6yvgbb3ws_ah2jjt2x7nj",
  "isExtra": false, "isNew": false, "operator": "TEMPORAL_RANGE", "sqlExpression":
  null, "subject": "processed_time"}, {"clause": "WHERE", "comparator": ["INGESTION"],
  "datasourceWarning": false, "expressionType": "SIMPLE", "filterOptionName": "filter_j43idvd6hqj_d7mxlsh0pk6",
  "isExtra": false, "isNew": false, "operator": "IN", "operatorId": "IN", "sqlExpression":
  null, "subject": "event_type"}, {"clause": "WHERE", "comparator": ["DP_INSTALLMENTS"],
  "datasourceWarning": false, "expressionType": "SIMPLE", "filterOptionName": "filter_rx16hr17hhq_uq8n2dq6v9",
  "isExtra": false, "isNew": false, "operator": "IN", "operatorId": "IN", "sqlExpression":
  null, "subject": "flow_type"}], "header_font_size": 0.3, "subtitle": "", "subtitle_font_size":
  0.125, "show_metric_name": false, "metric_name_font_size": 0.15, "y_axis_format":
  "SMART_NUMBER", "time_format": "smart_date", "conditional_formatting": [], "extra_form_data":
  {}, "dashboards": [5], "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: ee49051f-68d1-43ee-b368-75997cbe7a7b
version: 1.0.0
dataset_uuid: 44cd6a1f-195d-4811-9d7e-9c511a6f3bfe
