table_name: v_flow_file_monitoring
main_dttm_col: processed_time
currency_code_column: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: analytics
schema: dmt
sql: ''
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
folders: null
uuid: 44cd6a1f-195d-4811-9d7e-9c511a6f3bfe
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: processed_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: TIMESTAMP WITH TIME ZONE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: file_size_mb
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: month_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(20)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: operator_external_user_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(256)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: operator_type
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(256)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: event_type
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(256)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: flow_type
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(256)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: status
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(256)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: year_month
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(7)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: is_weekend
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: calendar_date
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: organization_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: processed_rows
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: row_count
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: file_size
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BIGINT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: day_of_month
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: cal_year
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: is_success
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: is_ingestion
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: is_export
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: fct_flow_file_pk
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: day_name_it
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: event_date_pk
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: operator_category
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: ''
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
- column_name: organization_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VARCHAR(256)
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  datetime_format: null
  extra: {}
version: 1.0.0
database_uuid: 798924eb-45fb-460e-95cf-90cf4cbb7ab9
