slice_name: Organization Heatmap
description: null
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 3__table
  viz_type: heatmap_v2
  slice_id: 17
  x_axis: access_date
  time_grain_sqla: P1D
  groupby: organization_name
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: access_date
  row_limit: 10000
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_desc
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: schemeGreens
  border_color:
    a: 1
    b: 0
    g: 0
    r: 0
  border_width: 0.5
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  x_axis_time_format: smart_date
  xAxisLabelRotation: 45
  show_legend: true
  show_percentage: true
  show_values: true
  normalized: true
  extra_form_data: {}
  dashboards:
  - 6
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"filters":[{"col":"access_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"access_date","label":"access_date","expressionType":"SQL","isColumnReference":true},"organization_name"],"metrics":["count"],"orderby":[["access_date",true],["organization_name",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[{"operation":"rank","options":{"metric":"count"}}]}],"form_data":{"datasource":"3__table","viz_type":"heatmap_v2","slice_id":17,"x_axis":"access_date","time_grain_sqla":"P1D","groupby":"organization_name","metric":"count","adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"access_date"}],"row_limit":10000,"sort_x_axis":"alpha_asc","sort_y_axis":"alpha_desc","normalize_across":"heatmap","legend_type":"continuous","linear_color_scheme":"schemeGreens","border_color":{"a":1,"b":0,"g":0,"r":0},"border_width":0.5,"xscale_interval":-1,"yscale_interval":-1,"left_margin":"auto","bottom_margin":"auto","value_bounds":[null,null],"y_axis_format":"SMART_NUMBER","x_axis_time_format":"smart_date","xAxisLabelRotation":45,"show_legend":true,"show_percentage":true,"show_values":true,"normalized":true,"extra_form_data":{},"dashboards":[6],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 2add103e-93f9-4c74-a927-5bf46b29bc22
version: 1.0.0
dataset_uuid: c6680ec3-d3bd-4303-a79c-c2800b3aca32
