slice_name: Pagamenti per capitoli
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 1__table
  viz_type: echarts_timeseries_bar
  slice_id: 28
  x_axis: section_description
  x_axis_sort: sum
  x_axis_sort_asc: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount_paid
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 11
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: cbf01977-1d5a-4374-a45f-4a8951eed851
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Pagati
    optionName: metric_jdszenvbqw_09wzgput8qjs
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount_reported
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 12
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: 80947855-c724-4dc1-87c1-c65a5835a4e1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Rendicontati
    optionName: metric_27vlc2ek9h5_bi5o47y7km
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount_cashed
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 13
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: c34c86c7-c425-4afe-9a64-60c14dfe9d99
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Incassati
    optionName: metric_bfo5v4xusho_a89w7122him
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date_receipt
  limit: 5
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: horizontal
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: blueItalia
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: $,.2f
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 8
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"date_receipt","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"section_description","label":"section_description","expressionType":"SQL","isColumnReference":true}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount_paid","description":null,"expression":"","filterable":true,"groupby":true,"id":11,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"cbf01977-1d5a-4374-a45f-4a8951eed851","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Pagati","optionName":"metric_jdszenvbqw_09wzgput8qjs","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount_reported","description":null,"expression":"","filterable":true,"groupby":true,"id":12,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"80947855-c724-4dc1-87c1-c65a5835a4e1","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Rendicontati","optionName":"metric_27vlc2ek9h5_bi5o47y7km","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount_cashed","description":null,"expression":"","filterable":true,"groupby":true,"id":13,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"c34c86c7-c425-4afe-9a64-60c14dfe9d99","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Incassati","optionName":"metric_bfo5v4xusho_a89w7122him","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount_paid","description":null,"expression":"","filterable":true,"groupby":true,"id":11,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"cbf01977-1d5a-4374-a45f-4a8951eed851","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Pagati","optionName":"metric_jdszenvbqw_09wzgput8qjs","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":5,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["section_description"],"columns":[],"aggregates":{"Pagati":{"operator":"mean"},"Rendicontati":{"operator":"mean"},"Incassati":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"1__table","viz_type":"echarts_timeseries_bar","slice_id":28,"x_axis":"section_description","x_axis_sort":"sum","x_axis_sort_asc":true,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount_paid","description":null,"expression":"","filterable":true,"groupby":true,"id":11,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"cbf01977-1d5a-4374-a45f-4a8951eed851","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Pagati","optionName":"metric_jdszenvbqw_09wzgput8qjs","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount_reported","description":null,"expression":"","filterable":true,"groupby":true,"id":12,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"80947855-c724-4dc1-87c1-c65a5835a4e1","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Rendicontati","optionName":"metric_27vlc2ek9h5_bi5o47y7km","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"amount_cashed","description":null,"expression":"","filterable":true,"groupby":true,"id":13,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"uuid":"c34c86c7-c425-4afe-9a64-60c14dfe9d99","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Incassati","optionName":"metric_bfo5v4xusho_a89w7122him","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"date_receipt"}],"limit":5,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"horizontal","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"blueItalia","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"$,.2f","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[8],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 53e3ad78-530f-4941-a732-c9524bc2049a
version: 1.0.0
dataset_uuid: f715b3f3-f8ba-436c-804e-864158a21517
