slice_name: Event Access Histogram
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 3__table
  viz_type: echarts_timeseries_bar
  slice_id: 16
  x_axis: access_date
  time_grain_sqla: P1D
  metrics:
  - count
  groupby:
  - event_type
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: access_date
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  sort_series_ascending: true
  color_scheme: SUPERSET_DEFAULT
  time_shift_color: true
  show_value: true
  stack: null
  only_total: true
  minorTicks: false
  zoomable: false
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: '%Y-%m-%d'
  xAxisLabelInterval: '0'
  y_axis_format: SMART_NUMBER
  minorSplitLine: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  truncateXAxis: false
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: false
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 6
query_context: '{"datasource": {"id": 3, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "access_date", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"time_grain_sqla": "P1D", "having": "", "where": ""}, "applied_time_extras":
  {}, "columns": [{"timeGrain": "P1D", "columnType": "BASE_AXIS", "sqlExpression":
  "access_date", "label": "access_date", "expressionType": "SQL", "isColumnReference":
  true}, "event_type"], "metrics": ["count"], "orderby": [["count", false]], "annotation_layers":
  [], "row_limit": 10000, "series_columns": ["event_type"], "series_limit": 0, "group_others_when_limit_reached":
  false, "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "time_offsets": [], "post_processing": [{"operation": "pivot", "options": {"index":
  ["access_date"], "columns": ["event_type"], "aggregates": {"count": {"operator":
  "mean"}}, "drop_missing_columns": false}}, {"operation": "rename", "options": {"columns":
  {"count": null}, "level": 0, "inplace": true}}, {"operation": "flatten"}]}], "form_data":
  {"datasource": "3__table", "viz_type": "echarts_timeseries_bar", "slice_id": 16,
  "x_axis": "access_date", "time_grain_sqla": "P1D", "metrics": ["count"], "groupby":
  ["event_type"], "adhoc_filters": [{"clause": "WHERE", "comparator": "No filter",
  "expressionType": "SIMPLE", "operator": "TEMPORAL_RANGE", "subject": "access_date"}],
  "row_limit": 10000, "truncate_metric": true, "show_empty_columns": true, "comparison_type":
  "values", "annotation_layers": [], "forecastPeriods": 10, "forecastInterval": 0.8,
  "orientation": "vertical", "x_axis_title_margin": 15, "y_axis_title_margin": 30,
  "y_axis_title_position": "Left", "sort_series_type": "sum", "sort_series_ascending":
  true, "color_scheme": "SUPERSET_DEFAULT", "time_shift_color": true, "show_value":
  true, "stack": null, "only_total": true, "minorTicks": false, "zoomable": false,
  "show_legend": true, "legendType": "scroll", "legendOrientation": "bottom", "x_axis_time_format":
  "%Y-%m-%d", "xAxisLabelInterval": "0", "y_axis_format": "SMART_NUMBER", "minorSplitLine":
  true, "truncateYAxis": false, "y_axis_bounds": [null, null], "truncateXAxis": false,
  "rich_tooltip": true, "showTooltipTotal": true, "showTooltipPercentage": false,
  "tooltipSortByMetric": false, "tooltipTimeFormat": "smart_date", "extra_form_data":
  {}, "dashboards": [6], "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 87fdbefa-2585-4216-a5a9-95b024dffd92
version: 1.0.0
dataset_uuid: c6680ec3-d3bd-4303-a79c-c2800b3aca32
tags: []
