slice_name: Heatmap
description: null
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 2__table
  viz_type: heatmap_v2
  slice_id: 12
  x_axis: year_month
  groupby: day_of_month
  metric:
    expressionType: SQL
    sqlExpression: COUNT(fct_flow_file_pk)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Operazioni
    optionName: metric_a5azsftr7_n3mr2x0p6j
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: processed_time
  row_limit: 10000
  sort_y_axis: alpha_asc
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: dark_blue
  border_color:
    a: 1
    b: 0
    g: 0
    r: 0
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  x_axis_time_format: smart_date
  show_legend: true
  show_percentage: true
  show_values: false
  normalized: false
  extra_form_data: {}
  dashboards:
  - 5
  annotation_layers: []
query_context: '{"datasource": {"id": 2, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "processed_time", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"having": "", "where": ""}, "applied_time_extras": {}, "columns": [{"columnType":
  "BASE_AXIS", "sqlExpression": "year_month", "label": "year_month", "expressionType":
  "SQL", "isColumnReference": true}, "day_of_month"], "metrics": [{"expressionType":
  "SQL", "sqlExpression": "COUNT(fct_flow_file_pk)", "column": null, "aggregate":
  null, "datasourceWarning": false, "hasCustomLabel": true, "label": "Operazioni",
  "optionName": "metric_a5azsftr7_n3mr2x0p6j"}], "orderby": [["day_of_month", true]],
  "annotation_layers": [], "row_limit": 10000, "series_limit": 0, "group_others_when_limit_reached":
  false, "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "post_processing": [{"operation": "rank", "options": {"metric": "Operazioni"}}]}],
  "form_data": {"datasource": "2__table", "viz_type": "heatmap_v2", "slice_id": 12,
  "x_axis": "year_month", "groupby": "day_of_month", "metric": {"expressionType":
  "SQL", "sqlExpression": "COUNT(fct_flow_file_pk)", "column": null, "aggregate":
  null, "datasourceWarning": false, "hasCustomLabel": true, "label": "Operazioni",
  "optionName": "metric_a5azsftr7_n3mr2x0p6j"}, "adhoc_filters": [{"clause": "WHERE",
  "comparator": "No filter", "expressionType": "SIMPLE", "operator": "TEMPORAL_RANGE",
  "subject": "processed_time"}], "row_limit": 10000, "sort_y_axis": "alpha_asc", "normalize_across":
  "heatmap", "legend_type": "continuous", "linear_color_scheme": "dark_blue", "border_color":
  {"a": 1, "b": 0, "g": 0, "r": 0}, "xscale_interval": -1, "yscale_interval": -1,
  "left_margin": "auto", "bottom_margin": "auto", "value_bounds": [null, null], "y_axis_format":
  "SMART_NUMBER", "x_axis_time_format": "smart_date", "show_legend": true, "show_percentage":
  true, "show_values": false, "normalized": false, "extra_form_data": {}, "dashboards":
  [5], "force": false, "result_format": "json", "result_type": "full"}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 3ba442ca-97ba-43aa-8c30-e12c931db64f
version: 1.0.0
dataset_uuid: 44cd6a1f-195d-4811-9d7e-9c511a6f3bfe
tags: []
