slice_name: Login-Success | Logout | Login-Failure
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 3__table
  viz_type: pie
  groupby:
  - event_type
  metric: count
  adhoc_filters:
  - clause: WHERE
    subject: access_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  row_limit: 100
  sort_by_metric: true
  color_scheme: SUPERSET_DEFAULT
  show_labels_threshold: 5
  roseType: null
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key_percent
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  label_line: true
  show_total: false
  outerRadius: 58
  donut: true
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 6
  annotation_layers: []
query_context: '{"datasource": {"id": 3, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "access_date", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"having": "", "where": ""}, "applied_time_extras": {}, "columns": ["event_type"],
  "metrics": ["count"], "orderby": [["count", false]], "annotation_layers": [], "row_limit":
  100, "series_limit": 0, "group_others_when_limit_reached": false, "order_desc":
  true, "url_params": {}, "custom_params": {}, "custom_form_data": {}, "post_processing":
  [{"operation": "contribution", "options": {"columns": ["count"], "rename_columns":
  ["count__contribution"]}}]}], "form_data": {"datasource": "3__table", "viz_type":
  "pie", "groupby": ["event_type"], "metric": "count", "adhoc_filters": [{"clause":
  "WHERE", "subject": "access_date", "operator": "TEMPORAL_RANGE", "comparator": "No
  filter", "expressionType": "SIMPLE"}], "row_limit": 100, "sort_by_metric": true,
  "color_scheme": "SUPERSET_DEFAULT", "show_labels_threshold": 5, "roseType": null,
  "show_legend": true, "legendType": "scroll", "legendOrientation": "top", "label_type":
  "key_percent", "number_format": "SMART_NUMBER", "date_format": "smart_date", "show_labels":
  true, "labels_outside": true, "label_line": true, "show_total": false, "outerRadius":
  58, "donut": true, "innerRadius": 30, "extra_form_data": {}, "dashboards": [6],
  "force": false, "result_format": "json", "result_type": "full"}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: null
uuid: 18a537c3-5922-48fa-b786-38b26ce3dcce
version: 1.0.0
dataset_uuid: c6680ec3-d3bd-4303-a79c-c2800b3aca32
tags: []
