slice_name: Today Login success
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 3__table
  viz_type: big_number
  slice_id: 15
  x_axis: access_date
  aggregation: LAST_VALUE
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_8mkqi5nd94l_3e5llsq7nbf
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: access_date
  - clause: WHERE
    comparator:
    - LOGIN_SUCCESS
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_uyfrckfb8vo_370plpfn2vd
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: event_type
  show_trend_line: true
  start_y_axis_at_zero: true
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  header_font_size: 0.6
  subheader_font_size: 0.4
  subtitle_font_size: 0.15
  show_metric_name: false
  metric_name_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  force_timestamp_formatting: false
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 6
  annotation_layers: []
query_context: '{"datasource": {"id": 3, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "access_date", "op": "TEMPORAL_RANGE", "val": "No filter"},
  {"col": "event_type", "op": "IN", "val": ["LOGIN_SUCCESS"]}], "extras": {"having":
  "", "where": ""}, "applied_time_extras": {}, "columns": [{"columnType": "BASE_AXIS",
  "sqlExpression": "access_date", "label": "access_date", "expressionType": "SQL",
  "isColumnReference": true}], "metrics": ["count"], "annotation_layers": [], "series_limit":
  0, "group_others_when_limit_reached": false, "order_desc": true, "url_params": {},
  "custom_params": {}, "custom_form_data": {}, "post_processing": [{"operation": "pivot",
  "options": {"index": ["access_date"], "columns": [], "aggregates": {"count": {"operator":
  "mean"}}, "drop_missing_columns": true}}, {"operation": "flatten"}]}], "form_data":
  {"datasource": "3__table", "viz_type": "big_number", "slice_id": 15, "x_axis": "access_date",
  "aggregation": "LAST_VALUE", "metric": "count", "adhoc_filters": [{"clause": "WHERE",
  "comparator": "No filter", "datasourceWarning": false, "expressionType": "SIMPLE",
  "filterOptionName": "filter_8mkqi5nd94l_3e5llsq7nbf", "isExtra": false, "isNew":
  false, "operator": "TEMPORAL_RANGE", "sqlExpression": null, "subject": "access_date"},
  {"clause": "WHERE", "comparator": ["LOGIN_SUCCESS"], "datasourceWarning": false,
  "expressionType": "SIMPLE", "filterOptionName": "filter_uyfrckfb8vo_370plpfn2vd",
  "isExtra": false, "isNew": false, "operator": "IN", "operatorId": "IN", "sqlExpression":
  null, "subject": "event_type"}], "show_trend_line": true, "start_y_axis_at_zero":
  true, "color_picker": {"a": 1, "b": 135, "g": 122, "r": 0}, "header_font_size":
  0.6, "subheader_font_size": 0.4, "subtitle_font_size": 0.15, "show_metric_name":
  false, "metric_name_font_size": 0.15, "y_axis_format": "SMART_NUMBER", "time_format":
  "smart_date", "force_timestamp_formatting": false, "rolling_type": "None", "extra_form_data":
  {}, "dashboards": [6], "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: e77f53f5-b90b-4824-bf5f-0dc86143ec44
version: 1.0.0
dataset_uuid: c6680ec3-d3bd-4303-a79c-c2800b3aca32
tags:
- core
