slice_name: Totali ripartiti per accertamenti
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 1__table
  viz_type: table
  slice_id: 8
  query_mode: aggregate
  groupby:
  - expressionType: SQL
    label: Accertamenti
    sqlExpression: assessment_description
  time_grain_sqla: P1D
  temporal_columns_lookup:
    date_receipt: true
    date_reporting: true
    date_treasury: true
    reference_date: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount_paid
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 11
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: cbf01977-1d5a-4374-a45f-4a8951eed851
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Totale pagati
    optionName: metric_zsknzclto7_sipzbwrm33g
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount_reported
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 12
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      uuid: 80947855-c724-4dc1-87c1-c65a5835a4e1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Totale rendicontati
    optionName: metric_9sg7vymwp0j_mgq7y5fcu4
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: amount_cashed
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 13
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: column
      type_generic: 0
      uuid: c34c86c7-c425-4afe-9a64-60c14dfe9d99
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Totale incassati
    optionName: metric_qec1qb0jzz8_97rhbyckh9
    sqlExpression: null
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date_receipt
  order_by_cols: []
  row_limit: 10000
  percent_metric_calculation: row_limit
  show_totals: true
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    Totale incassati:
      currencyFormat:
        symbol: EUR
        symbolPosition: suffix
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
    Totale pagati:
      currencyFormat:
        symbol: EUR
        symbolPosition: suffix
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
    Totale rendicontati:
      currencyFormat:
        symbol: EUR
        symbolPosition: suffix
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
  show_cell_bars: false
  color_pn: true
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 1
  annotation_layers: []
query_context: '{"datasource": {"id": 1, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "date_receipt", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"time_grain_sqla": "P1D", "having": "", "where": ""}, "applied_time_extras":
  {}, "columns": [{"expressionType": "SQL", "label": "Accertamenti", "sqlExpression":
  "assessment_description"}], "metrics": [{"aggregate": "SUM", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "amount_paid",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  11, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "NUMERIC", "type_generic": 0, "uuid": "cbf01977-1d5a-4374-a45f-4a8951eed851", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale pagati", "optionName": "metric_zsknzclto7_sipzbwrm33g",
  "sqlExpression": null}, {"aggregate": "SUM", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "amount_reported",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  12, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "NUMERIC", "type_generic": 0, "uuid": "80947855-c724-4dc1-87c1-c65a5835a4e1", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale rendicontati", "optionName": "metric_9sg7vymwp0j_mgq7y5fcu4",
  "sqlExpression": null}, {"aggregate": "SUM", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "amount_cashed",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  13, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "column", "type_generic": 0, "uuid": "c34c86c7-c425-4afe-9a64-60c14dfe9d99", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale incassati", "optionName": "metric_qec1qb0jzz8_97rhbyckh9",
  "sqlExpression": null}], "orderby": [[{"aggregate": "SUM", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "amount_paid",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  11, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "NUMERIC", "type_generic": 0, "uuid": "cbf01977-1d5a-4374-a45f-4a8951eed851", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale pagati", "optionName": "metric_zsknzclto7_sipzbwrm33g",
  "sqlExpression": null}, false]], "annotation_layers": [], "row_limit": 10000, "series_limit":
  0, "group_others_when_limit_reached": false, "order_desc": true, "url_params": {},
  "custom_params": {}, "custom_form_data": {}, "post_processing": [], "time_offsets":
  []}, {"filters": [{"col": "date_receipt", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"time_grain_sqla": "P1D", "having": "", "where": ""}, "applied_time_extras":
  {}, "columns": [], "metrics": [{"aggregate": "SUM", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "amount_paid",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  11, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "NUMERIC", "type_generic": 0, "uuid": "cbf01977-1d5a-4374-a45f-4a8951eed851", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale pagati", "optionName": "metric_zsknzclto7_sipzbwrm33g",
  "sqlExpression": null}, {"aggregate": "SUM", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "amount_reported",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  12, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "NUMERIC", "type_generic": 0, "uuid": "80947855-c724-4dc1-87c1-c65a5835a4e1", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale rendicontati", "optionName": "metric_9sg7vymwp0j_mgq7y5fcu4",
  "sqlExpression": null}, {"aggregate": "SUM", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "amount_cashed",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  13, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "column", "type_generic": 0, "uuid": "c34c86c7-c425-4afe-9a64-60c14dfe9d99", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale incassati", "optionName": "metric_qec1qb0jzz8_97rhbyckh9",
  "sqlExpression": null}], "annotation_layers": [], "row_limit": 0, "row_offset":
  0, "series_limit": 0, "group_others_when_limit_reached": false, "url_params": {},
  "custom_params": {}, "custom_form_data": {}, "post_processing": [], "time_offsets":
  []}], "form_data": {"datasource": "1__table", "viz_type": "table", "slice_id": 8,
  "query_mode": "aggregate", "groupby": [{"expressionType": "SQL", "label": "Accertamenti",
  "sqlExpression": "assessment_description"}], "time_grain_sqla": "P1D", "temporal_columns_lookup":
  {"date_receipt": true, "date_reporting": true, "date_treasury": true, "reference_date":
  true}, "metrics": [{"aggregate": "SUM", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "amount_paid", "description": null, "expression":
  "", "filterable": true, "groupby": true, "id": 11, "is_certified": false, "is_dttm":
  false, "python_date_format": null, "type": "NUMERIC", "type_generic": 0, "uuid":
  "cbf01977-1d5a-4374-a45f-4a8951eed851", "verbose_name": null, "warning_markdown":
  null}, "datasourceWarning": false, "expressionType": "SIMPLE", "hasCustomLabel":
  true, "label": "Totale pagati", "optionName": "metric_zsknzclto7_sipzbwrm33g", "sqlExpression":
  null}, {"aggregate": "SUM", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "amount_reported", "description": null,
  "expression": "", "filterable": true, "groupby": true, "id": 12, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "NUMERIC", "type_generic":
  0, "uuid": "80947855-c724-4dc1-87c1-c65a5835a4e1", "verbose_name": null, "warning_markdown":
  null}, "datasourceWarning": false, "expressionType": "SIMPLE", "hasCustomLabel":
  true, "label": "Totale rendicontati", "optionName": "metric_9sg7vymwp0j_mgq7y5fcu4",
  "sqlExpression": null}, {"aggregate": "SUM", "column": {"advanced_data_type": null,
  "certification_details": null, "certified_by": null, "column_name": "amount_cashed",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  13, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "column", "type_generic": 0, "uuid": "c34c86c7-c425-4afe-9a64-60c14dfe9d99", "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "Totale incassati", "optionName": "metric_qec1qb0jzz8_97rhbyckh9",
  "sqlExpression": null}], "all_columns": [], "percent_metrics": [], "adhoc_filters":
  [{"clause": "WHERE", "comparator": "No filter", "expressionType": "SIMPLE", "operator":
  "TEMPORAL_RANGE", "subject": "date_receipt"}], "order_by_cols": [], "row_limit":
  10000, "percent_metric_calculation": "row_limit", "show_totals": true, "table_timestamp_format":
  "smart_date", "allow_render_html": true, "column_config": {"Totale incassati": {"currencyFormat":
  {"symbol": "EUR", "symbolPosition": "suffix"}, "d3NumberFormat": ",.2f", "d3SmallNumberFormat":
  ",.2f"}, "Totale pagati": {"currencyFormat": {"symbol": "EUR", "symbolPosition":
  "suffix"}, "d3NumberFormat": ",.2f", "d3SmallNumberFormat": ",.2f"}, "Totale rendicontati":
  {"currencyFormat": {"symbol": "EUR", "symbolPosition": "suffix"}, "d3NumberFormat":
  ",.2f", "d3SmallNumberFormat": ",.2f"}}, "show_cell_bars": false, "color_pn": true,
  "conditional_formatting": [], "comparison_type": "values", "extra_form_data": {},
  "dashboards": [1], "force": false, "result_format": "json", "result_type": "full"},
  "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 1d7f17f7-e73a-4174-97ae-9275665d3196
version: 1.0.0
dataset_uuid: f715b3f3-f8ba-436c-804e-864158a21517
tags: []
